### ISSUE TITLE
Force refresh on puzzle exit

### ISSUE THREAD

**Issue by nathonius** [roygbyte/crossword.koplugin#12]
On my Kobo Libra 2, when exiting a puzzle, the screen only refreshes in a very small square, not the entire display. This leads to most of the puzzle still being displayed and me unable to see the list of puzzles unit tapping blindly on something that would otherwise cause a screen refresh.

Triggering a display refresh on puzzle exit seems like it would fix it.

**Comment by neilswann80** [comment]
I've hopefully addressed this in the open pull request.  Waiting roygbyte to test.

**Comment by roygbyte** [comment]
Should be addressed in [release 0.2.1](https://github.com/roygbyte/crossword.koplugin/releases/tag/0.2.1).
