### ISSUE TITLE
"How I develop plugins for KOReader" not accessible

### ISSUE THREAD

**Issue by Ceynou** [roygbyte/crossword.koplugin#13]
> This site is asking you to sign in.

I would love to read about it

**Comment by roygbyte** [comment]
Hi @Ceynou. It is still available on my gopher hole. You can see it using floodgap, a gopher proxy, or Lynx. Here's a link to the former: https://gopher.floodgap.com/gopher/gw?a=gopher%3A%2F%2Froygbyte.com%2F1%2Fhow_i_develop_plugins_for_koreader.gph

**Comment by Ceynou** [comment]
Thank you kind sir
