### ISSUE TITLE
Doesn't show up in plugin management

### ISSUE THREAD

**Issue by junnunkarim** [roygbyte/crossword.koplugin#2]
I am using a jailbroken kindle voyage. I have did the all the instructions from the readme but crossword isn't showing up in plugin management. Other plugins like calculator shows up but crossword isn't. What could be the issue?

**Comment by roygbyte** [comment]
Hi @junnunkarim! You'll find the plugin under the left-most menu item in the toolbar. I can't remember what the button is called... 

Probably, it's not the best place for the plugin. (The decision to put it there is a hold-over from when I was developing it).

**Comment by junnunkarim** [comment]
Hello There @roygbyte!
Isn't the plugin menu in the ```<tool_icon>/more_tools``` section? But I did search everywhere in the menu, still I couldn't find it. I also added the calculator plugin form https://github.com/koreader/contrib and it shows up fine under ```<tool_icon>/more_tools```. But the crossword plugin is not showing up.

**Comment by roygbyte** [comment]
Oh, that is strange. I defined the `sorting_hint` here:

https://github.com/roygbyte/crossword.koplugin/blob/39fce98e932e3dd3630f1867397a01a2ed125bba/main.lua#L43-L51

You could try changing the value of `sorting_hint` to `"more_tools"` and that may resolve your issue.

**Comment by junnunkarim** [comment]
> You could try changing the value of `sorting_hint` to `"more_tools"` and that may resolve your issue.

Well, I just tested it but still not showing up.
What version of koreader are you using? Did they change any plugin related functions in the latest version?

**Comment by roygbyte** [comment]
Could also be that there is a bug in my code! I will check later and see (all a person has to do is run `luacheck plugins/crossword.koplugin/*` to see if the Lua script has errors.)

**Comment by junnunkarim** [comment]
Sorry for the late reply.
Yes, I did clone the submodule.

**Comment by roygbyte** [comment]
Not sure what the issue could be! But I'm determined to figure this out!! Nothing would make me happier than knowing someone other than me is enjoying this plugin 😊

It may or may not make a difference, but I pushed an update to the code last night. You might try to give that a go?

**Comment by junnunkarim** [comment]
Hey Thanks. I respect your determination and goodwill.

I did try out the latest commit but still the problem exists. Btw what version of koreader are you using?
I think I should try out that version.

**Comment by roygbyte** [comment]
I am using [2022.03.1](https://github.com/koreader/koreader/tree/v2022.03.1). Seems like you are using that too. It could be worth looking inside the `crash.log` file. Maybe check to see if the plugin is at least loaded along with the other plugins, like evidenced below: 

``` sh
04/30/22-15:58:13 DEBUG FM loaded plugin autosuspend at plugins/autosuspend.koplugin
04/30/22-15:58:13 DEBUG FM loaded plugin autowarmth at plugins/autowarmth.koplugin
04/30/22-15:58:13 DEBUG FM loaded plugin backgroundrunner at plugins/backgroundrunner.koplugin
04/30/22-15:58:13 DEBUG FM loaded plugin batterystat at plugins/batterystat.koplugin
04/30/22-15:58:13 DEBUG FM loaded plugin bookshortcuts at plugins/bookshortcuts.koplugin
04/30/22-15:58:13 DEBUG FM loaded plugin calibre at plugins/calibre.koplugin
04/30/22-15:58:13 DEBUG FM loaded plugin coverbrowser at plugins/coverbrowser.koplugin
04/30/22-15:58:13 DEBUG FM loaded plugin crossword at plugins/crossword.koplugin
```

**Comment by junnunkarim** [comment]
I took a look at the crash log (debug logging turned off) and it seems koreader can't find a module named ```gridinput```.

```
05/21/22-15:58:55 INFO  Loading plugins from directory: plugins
ffi.load: sqlite3
05/21/22-15:58:56 WARN  Error when loading plugins/crossword.koplugin/main.lua plugins/crossword.koplugin/gridview.lua:17: module 'gridinput' not found:
	no field package.preload['gridinput']
	no file 'plugins/crossword.koplugin/gridinput.lua'
	no file 'common/gridinput.lua'
	no file 'rocks/share/lua/5.1/gridinput.lua'
	no file 'frontend/gridinput.lua'
	no file './gridinput.lua'
	no file '/usr/local/share/luajit-2.1.0-beta3/gridinput.lua'
	no file '/usr/local/share/lua/5.1/gridinput.lua'
	no file '/usr/local/share/lua/5.1/gridinput/init.lua'
	no file 'plugins/crossword.koplugin/lib/gridinput.so'
	no file 'common/gridinput.so'
	no file 'common/gridinput.dll'
	no file '/usr/lib/lua/gridinput.so'
	no file 'rocks/lib/lua/5.1/gridinput.so'
	no file './gridinput.so'
	no file '/usr/local/lib/lua/5.1/gridinput.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by roygbyte** [comment]
Welp, that's totally my doing. A good reminder for me to test from a fresh checkout, and not my working directory.

**Comment by junnunkarim** [comment]
Thanks, it works now.
