### ISSUE TITLE
Unable to directly select squares in first five rows

### ISSUE THREAD

**Issue by neilswann80** [roygbyte/crossword.koplugin#8]
**_Only just discovered this plugin and am instantly a huge fan!  I flippin' love it.  A big thankyou for all the time you've spent on it._** 

I'm running the plugin through koreader installed on a PocketBook 632 for reference.

`I'm unable to directly select cells/squares in roughly the first five rows.  I say roughly because it changes from puzzle to puzzle, but is roughly the first 75 squares +- 6 squares.  (for the puzzles I've tested thus far.)`

This isn't a huge problem as I can still use the cursor keys to move through that area, but not being able to directly select a specific square in that area for deletion certainly makes for a clumsier experience.

I'm not hugely familiar with LUA, having only made minor changes to existing koreader plugins; but could you suggest which file and function I could try to tweak?

My guess would be `gridsquare.lua`  within function `GridSquare:init()`  ???

Thanks in advance.

**Comment by roygbyte** [comment]
Hi, thanks for the bug report. aero31areo mentioned a similar [issue](https://github.com/roygbyte/crossword.koplugin/issues/6), and I've experienced (and coped with) this bug to. For me, it only affects the top left square. So that's interesting you say it affects a few squares. I'll take a look in the next week or so.

**Comment by neilswann80** [comment]
FYI... my problem was caused by an older version of gameview.lua in the latest release.  Overwriting this with the latest solved the issue.

`if(self.puzzle:getSquareAtPos(row_num, col_num)) then
   return
 end`

Seemed to be causing the issue which has been replaced by:
`if not self.puzzle:getSolveByIndex(maybe_square_index) then
   return
 end
